stages:
  - build
  - push

variables:
  VERSION: "1.0.0"
  REGISTRY: "registry.ahurix.com"
  PROJECT: "tools"
  IMAGE_NAME: "${REGISTRY}/${PROJECT}/price_publisher"

default:
  # Verify dependencies are available
    - docker --version
    - make --version
    # Registry login
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY
    
build-job:
  stage: build
  script:
    - make build

push-job:
  stage: push
  script:
    - make push
  only:
    - main