stages:
  - build
  - push
  - deploy

variables:
  VERSION: "1.0.0"
  REGISTRY: "registry.ahurix.com"
  PROJECT: "tools"
  IMAGE_NAME: "${REGISTRY}/${PROJECT}/price_publisher"
  INFRA_PROJECT_ID: "12345"  # Your infrastructure project ID

default:
  before_script:
    - docker --version
    - make --version
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY

build-job:
  stage: build
  script:
    - make build

push-job:
  stage: push
  script:
    - make push
  only:
    - main

deploy:
  stage: trigger-deploy
  trigger:
    project: your-group/infrastructure
    branch: main
    strategy: depend
  variables:
    SERVICE_IMAGE_TAG: $CI_COMMIT_SHA
    SERVICE_NAME: "price_publisher"
    TRIGGERED_BY: $CI_PROJECT_NAME
    TRIGGERED_BY_PIPELINE: $CI_PIPELINE_ID
  only:
    - main
  dependencies:
    - push-job