stages:
  - build
  - push

variables:
  VERSION: "1.0.0"
  REGISTRY: "registry.ahurix.com"
  PROJECT: "tools"
  IMAGE_NAME: "${REGISTRY}/${PROJECT}/price_publisher"

default:
  before_script:
    # Check and install Docker if needed
    - if ! command -v docker &> /dev/null; then
        echo "Installing Docker...";
        curl -fsSL https://get.docker.com -o get-docker.sh;
        sudo sh get-docker.sh;
        sudo usermod -aG docker $USER;
      fi
    # Install make if needed
    - if ! command -v make &> /dev/null; then
        echo "Installing make...";
        sudo apt update && sudo apt install -y make;
      fi
    # Registry login
    - echo "$CI_REGISTRY_PASSWORD" | sudo docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY

build-job:
  stage: build
  script:
    - make build

push-job:
  stage: push
  script:
    - make push
  only:
    - main