stages:
  - build
  - push
  - deploy

variables:
  VERSION: "1.0.0"
  REGISTRY: "registry.ahurix.com"
  PROJECT: "tools"
  IMAGE_NAME: "${REGISTRY}/${PROJECT}/price_publisher"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker --version
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $REGISTRY

build-job:
  stage: build
  script:
    - docker build -t ${IMAGE_NAME}:${VERSION} -t ${IMAGE_NAME}:latest .

push-job:
  stage: push
  script:
    - docker push ${IMAGE_NAME}:${VERSION}
    - docker push ${IMAGE_NAME}:latest
  only:
    - feature/k8s_enabled
    - main

deploy-dev:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  variables:
    KUBECONFIG: /tmp/kubeconfig
  before_script:
    - echo "$KUBE_CONFIG_DEV" | base64 -d > $KUBECONFIG
    - chmod 600 $KUBECONFIG
    - kubectl cluster-info
  script:
    - kubectl apply -k k8s/overlays/dev
    - kubectl rollout status deployment/price-publisher -n price-publisher --timeout=300s
    - kubectl get pods -n price-publisher
  environment:
    name: development
    url: http://dev.ahurix.com:30555
  only:
    - feature/k8s_enabled
    - main

deploy-prod:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  variables:
    KUBECONFIG: /tmp/kubeconfig
  before_script:
    - echo "$KUBE_CONFIG_PROD" | base64 -d > $KUBECONFIG
    - chmod 600 $KUBECONFIG
    - kubectl cluster-info
  script:
    - kubectl apply -k k8s/overlays/prod
    - kubectl rollout status deployment/price-publisher -n price-publisher --timeout=300s
    - kubectl get pods -n price-publisher
  environment:
    name: production
    url: http://k3s.ahurix.com:30555
  only:
    - main
  when: manual