apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-publisher
spec:
  replicas: 2  # High availability in production
  template:
    spec:
      containers:
      - name: price-publisher
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "production"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - price-publisher
              topologyKey: kubernetes.io/hostname