apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-publisher
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: price-publisher
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: ENVIRONMENT
          value: "production"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - price-publisher
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        kubernetes.io/hostname: production  # CHANGED: now targets production node
        kubernetes.io/os: linux