apiVersion: v1
kind: ServiceAccount
metadata:
  name: price-publisher
  namespace: price-publisher
  labels:
    app.kubernetes.io/name: price-publisher
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: price-publisher-leader-election
  namespace: price-publisher
  labels:
    app.kubernetes.io/name: price-publisher
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: price-publisher-leader-election
  namespace: price-publisher
  labels:
    app.kubernetes.io/name: price-publisher
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: price-publisher-leader-election
subjects:
- kind: ServiceAccount
  name: price-publisher
  namespace: price-publisher