apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-publisher
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: price-publisher
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: ENVIRONMENT
          value: "development"
      nodeSelector:
        kubernetes.io/hostname: development  # Target worker node
        kubernetes.io/os: linux